@startuml

state ABLE_STATE_POWER_DOWN
state ABLE_STATE_IDLE
state ABLE_STATE_ADV
state ABLE_STATE_CONN
state ABLE_STATE_CONN_ADV

[*] -> ABLE_STATE_POWER_DOWN
ABLE_STATE_POWER_DOWN --> ABLE_STATE_IDLE : able_init()

ABLE_STATE_IDLE -> ABLE_STATE_ADV : able_adv_start()
ABLE_STATE_IDLE <- ABLE_STATE_ADV : able_adv_stop()
ABLE_STATE_IDLE <[dotted]- ABLE_STATE_ADV : on timeout (X)

ABLE_STATE_ADV -> ABLE_STATE_CONN : on connect

ABLE_STATE_CONN -[dotted]-> ABLE_STATE_IDLE : all clients desconected

ABLE_STATE_CONN -> ABLE_STATE_CONN_ADV : adv startet with connected clients
ABLE_STATE_CONN <[dotted]- ABLE_STATE_CONN_ADV : on timeout (X)

ABLE_STATE_IDLE -up-> ABLE_STATE_POWER_DOWN : able_deinit()

@enduml
